//next.js
import type { Metadata } from "next";
//font
import { Geist, Barlow } from "next/font/google";
//Global.css
import "./globals.css";
//theme
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const barlowFont = Barlow({
  subsets:['latin'],
  weight:['500','700'],
  variable: "--font-barlow",
})

//metadata
export const metadata: Metadata = {
  title: "GoShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"suppressHydrationWarning>
      <body
        className={`${geistSans.className} ${barlowFont.variable}`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
